//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Harvester.Windows.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class MessageColor : global::System.Configuration.ApplicationSettingsBase {
        
        private static MessageColor defaultInstance = ((MessageColor)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new MessageColor())));
        
        public static MessageColor Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color PrimaryBackColor {
            get {
                return ((global::System.Drawing.Color)(this["PrimaryBackColor"]));
            }
            set {
                this["PrimaryBackColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Red")]
        public global::System.Drawing.Color FatalBackColor {
            get {
                return ((global::System.Drawing.Color)(this["FatalBackColor"]));
            }
            set {
                this["FatalBackColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color FatalForeColor {
            get {
                return ((global::System.Drawing.Color)(this["FatalForeColor"]));
            }
            set {
                this["FatalForeColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color ErrorBackColor {
            get {
                return ((global::System.Drawing.Color)(this["ErrorBackColor"]));
            }
            set {
                this["ErrorBackColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Red")]
        public global::System.Drawing.Color ErrorForeColor {
            get {
                return ((global::System.Drawing.Color)(this["ErrorForeColor"]));
            }
            set {
                this["ErrorForeColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color WarningBackColor {
            get {
                return ((global::System.Drawing.Color)(this["WarningBackColor"]));
            }
            set {
                this["WarningBackColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Yellow")]
        public global::System.Drawing.Color WarningForeColor {
            get {
                return ((global::System.Drawing.Color)(this["WarningForeColor"]));
            }
            set {
                this["WarningForeColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color InformationBackColor {
            get {
                return ((global::System.Drawing.Color)(this["InformationBackColor"]));
            }
            set {
                this["InformationBackColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color InformationForeColor {
            get {
                return ((global::System.Drawing.Color)(this["InformationForeColor"]));
            }
            set {
                this["InformationForeColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color DebugBackColor {
            get {
                return ((global::System.Drawing.Color)(this["DebugBackColor"]));
            }
            set {
                this["DebugBackColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Gray")]
        public global::System.Drawing.Color DebugForeColor {
            get {
                return ((global::System.Drawing.Color)(this["DebugForeColor"]));
            }
            set {
                this["DebugForeColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color TraceBackColor {
            get {
                return ((global::System.Drawing.Color)(this["TraceBackColor"]));
            }
            set {
                this["TraceBackColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DarkSlateGray")]
        public global::System.Drawing.Color TraceForeColor {
            get {
                return ((global::System.Drawing.Color)(this["TraceForeColor"]));
            }
            set {
                this["TraceForeColor"] = value;
            }
        }
    }
}
